test: &default

  # Credentials for REST APIs
  client_id: ARC9TxBnrZfz6QvQVrCgM-Go_1uPKFTxqGwp01g4PurBG1nwyI6rSs3nCg9t
  client_secret: EH-KQhA2py6ceSlX6LeKnmL_J3zlzub1_9-tAdwwFaZWEelokuO4XT9P7G1H

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: felixweberizer-facilitator_api1.gmail.com
  password: 1403427501
  signature: A52vUjTdg27l.FtdMJVB.9V0FVlyAxDd97hmgyI-pNYAP.kyKFi2BNS7
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: felixweberizer-facilitator@gmail.com 

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live

